### ISSUE TITLE
pip install failing on mws3 

### ISSUE THREAD

**Issue by S-Stephen** [cuedpc/edpcmentoring#27]
when executing pip install in deploy/setup_mws.py 

(ImportError: No module named packaging.version)

works on other envs (docker image mws3)

**Comment by rjw57** [comment]
On 2017-02-13 16:23, StephenS wrote:
> when executing pip install in deploy/setup_mws.py
> 
> (ImportError: No module named packaging.version)
> 
> works on other envs (docker image mws3)

What's the full traceback? A quick look at setup_mws.py doesn't indicate 
that packaging is used,

Alternatively, adding "packaging" to the requirements.txt might help.

-- 
Dr Rich Wareham

**Comment by S-Stephen** [comment]
MWS3 is installing packages using --system-site-packages (as we have no c compiler for ucam-webauth) I wonder whether the existence of some site packages are the source of the issue.

Output from 'pip install -r ./requirements_mws3.txt -r ./dev-requirements.txt' below 

Downloading/unpacking dj-database-url==0.4.0 (from -r ./requirements_mws3.txt (line 3))
  Downloading dj-database-url-0.4.0.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/dj-database-url/setup.py) egg_info for package dj-database-url
    
Downloading/unpacking django-annoying (from -r ./requirements_mws3.txt (line 4))
  Downloading django_annoying-0.10.3-py2-none-any.whl
Downloading/unpacking django-crispy-forms (from -r ./requirements_mws3.txt (line 5))
Downloading/unpacking django-debug-toolbar (from -r ./requirements_mws3.txt (line 6))
Downloading/unpacking django-email-log (from -r ./requirements_mws3.txt (line 7))
  Downloading django_email_log-0.2.0-py2-none-any.whl
Downloading/unpacking django-extensions (from -r ./requirements_mws3.txt (line 8))
Downloading/unpacking django-filter (from -r ./requirements_mws3.txt (line 9))
Downloading/unpacking django-tables2 (from -r ./requirements_mws3.txt (line 10))
  Running setup.py (path:/tmp/pip-build-wMSfMK/django-tables2/setup.py) egg_info for package django-tables2
    
    warning: no files found matching 'README.md'
Downloading/unpacking django-ucamwebauth (from -r ./requirements_mws3.txt (line 11))
  Downloading django-ucamwebauth-1.3.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/django-ucamwebauth/setup.py) egg_info for package django-ucamwebauth
    
Downloading/unpacking django-role-permissions (from -r ./requirements_mws3.txt (line 12))
  Downloading django-role-permissions-1.2.3.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/django-role-permissions/setup.py) egg_info for package django-role-permissions
    
Downloading/unpacking django<1.10 (from -r ./requirements_mws3.txt (line 13))
Downloading/unpacking future (from -r ./requirements_mws3.txt (line 14))
  Running setup.py (path:/tmp/pip-build-wMSfMK/future/setup.py) egg_info for package future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from -r ./requirements_mws3.txt (line 15))
Downloading/unpacking whitenoise (from -r ./requirements_mws3.txt (line 16))
  Downloading whitenoise-3.3.0-py2.py3-none-any.whl
Downloading/unpacking djangorestframework (from -r ./requirements_mws3.txt (line 17))
Downloading/unpacking markdown (from -r ./requirements_mws3.txt (line 18))
  Running setup.py (path:/tmp/pip-build-wMSfMK/markdown/setup.py) egg_info for package markdown
    
Downloading/unpacking django-angular (from -r ./requirements_mws3.txt (line 19))
  Downloading django-angular-0.8.4.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/django-angular/setup.py) egg_info for package django-angular
    
    warning: no files found matching 'CONTRIBUTIONS.md'
    warning: no files found matching '*.py' under directory 'djangular'
Downloading/unpacking mock (from -r ./requirements_mws3.txt (line 23))
Downloading/unpacking pinax-notifications (from -r ./requirements_mws3.txt (line 25))
  Downloading pinax_notifications-4.0.0-py2.py3-none-any.whl
Downloading/unpacking fake-factory (from -r ./dev-requirements.txt (line 3))
Downloading/unpacking ipython (from -r ./dev-requirements.txt (line 4))
Downloading/unpacking pylint (from -r ./dev-requirements.txt (line 5))
Downloading/unpacking werkzeug (from -r ./dev-requirements.txt (line 6))
Downloading/unpacking sqlparse>=0.2.0 (from django-debug-toolbar->-r ./requirements_mws3.txt (line 6))
  Downloading sqlparse-0.2.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.2 in /usr/lib/python2.7/dist-packages (from django-extensions->-r ./requirements_mws3.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL in /usr/lib/python2.7/dist-packages (from django-ucamwebauth->-r ./requirements_mws3.txt (line 11))
Downloading/unpacking django-discover-runner (from django-role-permissions->-r ./requirements_mws3.txt (line 12))
  Downloading django_discover_runner-1.0-py2.py3-none-any.whl
Downloading/unpacking funcsigs>=1 (from mock->-r ./requirements_mws3.txt (line 23))
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Downloading/unpacking pbr>=0.11 (from mock->-r ./requirements_mws3.txt (line 23))
Downloading/unpacking django-appconf>=1.0.1 (from pinax-notifications->-r ./requirements_mws3.txt (line 25))
  Downloading django_appconf-1.0.2-py2.py3-none-any.whl
Downloading/unpacking pickleshare (from ipython->-r ./dev-requirements.txt (line 4))
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Downloading/unpacking pathlib2 (from ipython->-r ./dev-requirements.txt (line 4))
  Downloading pathlib2-2.2.1-py2.py3-none-any.whl
Downloading/unpacking setuptools>=18.5 (from ipython->-r ./dev-requirements.txt (line 4))
Downloading/unpacking traitlets>=4.2 (from ipython->-r ./dev-requirements.txt (line 4))
Downloading/unpacking simplegeneric>0.8 (from ipython->-r ./dev-requirements.txt (line 4))
  Downloading simplegeneric-0.8.1.zip
  Running setup.py (path:/tmp/pip-build-wMSfMK/simplegeneric/setup.py) egg_info for package simplegeneric
    
Downloading/unpacking prompt-toolkit>=1.0.4,<2.0.0 (from ipython->-r ./dev-requirements.txt (line 4))
Downloading/unpacking pygments (from ipython->-r ./dev-requirements.txt (line 4))
Downloading/unpacking pexpect (from ipython->-r ./dev-requirements.txt (line 4))
Downloading/unpacking decorator (from ipython->-r ./dev-requirements.txt (line 4))
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Downloading/unpacking backports.shutil-get-terminal-size (from ipython->-r ./dev-requirements.txt (line 4))
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Downloading/unpacking configparser (from pylint->-r ./dev-requirements.txt (line 5))
  Downloading configparser-3.5.0.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/configparser/setup.py) egg_info for package configparser
    
Downloading/unpacking backports.functools-lru-cache (from pylint->-r ./dev-requirements.txt (line 5))
  Downloading backports.functools_lru_cache-1.3-py2.py3-none-any.whl
Downloading/unpacking isort>=4.2.5 (from pylint->-r ./dev-requirements.txt (line 5))
Downloading/unpacking mccabe (from pylint->-r ./dev-requirements.txt (line 5))
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Downloading/unpacking astroid>=1.4.5,<1.5.0 (from pylint->-r ./dev-requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.2.1 in /usr/lib/python2.7/dist-packages (from pyOpenSSL->django-ucamwebauth->-r ./requirements_mws3.txt (line 11))
Downloading/unpacking scandir (from pathlib2->ipython->-r ./dev-requirements.txt (line 4))
  Downloading scandir-1.4.zip
  Running setup.py (path:/tmp/pip-build-wMSfMK/scandir/setup.py) egg_info for package scandir
    
    warning: no files found matching 'README.md'
    'test/testdir/subdir/unicodƏ.txt' not ANSI_X3.4-1968 encodable -- skipping
    'test/testdir/subdir/unidirƏ/file1.txt' not ANSI_X3.4-1968 encodable -- skipping
Downloading/unpacking appdirs>=1.4.0 (from setuptools>=18.5->ipython->-r ./dev-requirements.txt (line 4))
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Downloading/unpacking packaging>=16.8 (from setuptools>=18.5->ipython->-r ./dev-requirements.txt (line 4))
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking ipython-genutils (from traitlets>=4.2->ipython->-r ./dev-requirements.txt (line 4))
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Downloading/unpacking enum34 (from traitlets>=4.2->ipython->-r ./dev-requirements.txt (line 4))
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking wcwidth (from prompt-toolkit>=1.0.4,<2.0.0->ipython->-r ./dev-requirements.txt (line 4))
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Downloading/unpacking ptyprocess>=0.5 (from pexpect->ipython->-r ./dev-requirements.txt (line 4))
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Downloading/unpacking wrapt (from astroid>=1.4.5,<1.5.0->pylint->-r ./dev-requirements.txt (line 5))
  Downloading wrapt-1.10.8.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/wrapt/setup.py) egg_info for package wrapt
    
Downloading/unpacking lazy-object-proxy (from astroid>=1.4.5,<1.5.0->pylint->-r ./dev-requirements.txt (line 5))
  Downloading lazy-object-proxy-1.2.2.tar.gz
  Running setup.py (path:/tmp/pip-build-wMSfMK/lazy-object-proxy/setup.py) egg_info for package lazy-object-proxy
    
    warning: no directories found matching 'examples'
    warning: no files found matching '.isort.cfg'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): cffi>=0.8 in /usr/lib/python2.7/dist-packages (from cryptography>=0.2.1->pyOpenSSL->django-ucamwebauth->-r ./requirements_mws3.txt (line 11))
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools>=18.5->ipython->-r ./dev-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/dist-packages (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL->django-ucamwebauth->-r ./requirements_mws3.txt (line 11))
Installing collected packages: dj-database-url, django-annoying, django-crispy-forms, django-debug-toolbar, django-email-log, django-extensions, django-filter, django-tables2, django-ucamwebauth, django-role-permissions, django, future, whitenoise, djangorestframework, markdown, django-angular, mock, pinax-notifications, fake-factory, ipython, pylint, werkzeug, sqlparse, django-discover-runner, funcsigs, pbr, django-appconf, pickleshare, pathlib2, setuptools, traitlets, simplegeneric, prompt-toolkit, pygments, pexpect, decorator, backports.shutil-get-terminal-size, configparser, backports.functools-lru-cache, isort, mccabe, astroid, scandir, appdirs, packaging, ipython-genutils, enum34, wcwidth, ptyprocess, wrapt, lazy-object-proxy, pyparsing
  Running setup.py install for dj-database-url
    
  Running setup.py install for django-tables2
    
    warning: no files found matching 'README.md'
  Running setup.py install for django-ucamwebauth
    
  Running setup.py install for django-role-permissions
    
  Running setup.py install for future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
    Installing pasteurize script to /replicated/www/default/admindir/edpcmentoring/env/bin
    Installing futurize script to /replicated/www/default/admindir/edpcmentoring/env/bin
  Running setup.py install for markdown
    changing mode of build/scripts-2.7/markdown_py from 664 to 775
    Converting docs/release-2.2.1.txt -> build/docs/release-2.2.1.html
    Converting docs/release-2.1.1.txt -> build/docs/release-2.1.1.html
    Converting docs/release-2.0.txt -> build/docs/release-2.0.html
    Converting docs/reference.txt -> build/docs/reference.html
    Converting docs/release-2.0.1.txt -> build/docs/release-2.0.1.html
    Converting docs/cli.txt -> build/docs/cli.html
    Converting docs/release-2.5.txt -> build/docs/release-2.5.html
    Converting docs/release-2.1.0.txt -> build/docs/release-2.1.0.html
    Converting docs/release-2.0.2.txt -> build/docs/release-2.0.2.html
    Converting docs/release-2.2.0.txt -> build/docs/release-2.2.0.html
    Converting docs/release-2.6.txt -> build/docs/release-2.6.html
    Converting docs/siteindex.txt -> build/docs/siteindex.html
    Converting docs/install.txt -> build/docs/install.html
    Converting docs/index.txt -> build/docs/index.html
    Converting docs/authors.txt -> build/docs/authors.html
    Converting docs/release-2.3.txt -> build/docs/release-2.3.html
    Converting docs/change_log.txt -> build/docs/change_log.html
    Converting docs/release-2.4.txt -> build/docs/release-2.4.html
    Converting docs/test_suite.txt -> build/docs/test_suite.html
    Converting docs/extensions/meta_data.txt -> build/docs/extensions/meta_data.html
    Converting docs/extensions/attr_list.txt -> build/docs/extensions/attr_list.html
    Converting docs/extensions/nl2br.txt -> build/docs/extensions/nl2br.html
    Converting docs/extensions/extra.txt -> build/docs/extensions/extra.html
    Converting docs/extensions/sane_lists.txt -> build/docs/extensions/sane_lists.html
    Converting docs/extensions/fenced_code_blocks.txt -> build/docs/extensions/fenced_code_blocks.html
    Converting docs/extensions/definition_lists.txt -> build/docs/extensions/definition_lists.html
    Converting docs/extensions/toc.txt -> build/docs/extensions/toc.html
    Converting docs/extensions/wikilinks.txt -> build/docs/extensions/wikilinks.html
    Converting docs/extensions/abbreviations.txt -> build/docs/extensions/abbreviations.html
    Converting docs/extensions/footnotes.txt -> build/docs/extensions/footnotes.html
    Converting docs/extensions/index.txt -> build/docs/extensions/index.html
    Converting docs/extensions/api.txt -> build/docs/extensions/api.html
    Converting docs/extensions/header_id.txt -> build/docs/extensions/header_id.html
    Converting docs/extensions/smarty.txt -> build/docs/extensions/smarty.html
    Converting docs/extensions/admonition.txt -> build/docs/extensions/admonition.html
    Converting docs/extensions/smart_strong.txt -> build/docs/extensions/smart_strong.html
    Converting docs/extensions/code_hilite.txt -> build/docs/extensions/code_hilite.html
    Converting docs/extensions/tables.txt -> build/docs/extensions/tables.html
    
    changing mode of /replicated/www/default/admindir/edpcmentoring/env/bin/markdown_py to 775
  Running setup.py install for django-angular
    
    warning: no files found matching 'CONTRIBUTIONS.md'
    warning: no files found matching '*.py' under directory 'djangular'
Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/abstract_class_instantiated_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/abstract_class_instantiated_py3.py", line 14
    class GoodClass(object, metaclass=abc.ABCMeta):
                                     ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/abstract_method_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/abstract_method_py3.py", line 35
    class Structure(object, metaclass=abc.ABCMeta):
                                     ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/async_functions.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/async_functions.py", line 5
    async def next(): # [redefined-builtin]
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/bad_exception_context.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/bad_exception_context.py", line 14
    raise IndexError from 1 # [bad-exception-context]
                        ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/class_members_py30.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/class_members_py30.py", line 34
    class TestMetaclass(object, metaclass=ABCMeta):
                                         ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/continue_in_finally.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/continue_in_finally.py", line 9
    continue # [continue-in-finally]
SyntaxError: 'continue' not supported inside 'finally' clause

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/duplicate_argument_name.py ...
SyntaxError: duplicate argument '_' in function definition (duplicate_argument_name.py, line 4)

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/exec_used_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/exec_used_py3.py", line 4
    exec('a = 1', globals={}) # [exec-used]
                         ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/invalid_star_assignment_target.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/invalid_star_assignment_target.py", line 3
    *FIRST = [1, 2, 3] # [invalid-star-assignment-target]
    ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/iterable_context_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/iterable_context_py3.py", line 11
    class SomeClass(metaclass=Meta):
                             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/mapping_context_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/mapping_context_py3.py", line 15
    class SomeClass(metaclass=Meta):
                             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/membership_protocol_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/membership_protocol_py3.py", line 20
    class IterableClass(metaclass=MetaOldIterable):
                                 ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/misplaced_future.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/misplaced_future.py", line 3
    from __future__ import print_function # [misplaced-future]
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/nonlocal_and_global.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/nonlocal_and_global.py", line 5
    nonlocal missing
                   ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/nonlocal_without_binding.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/nonlocal_without_binding.py", line 9
    nonlocal a
             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/not_async_context_manager.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/not_async_context_manager.py", line 50
    async def bad_coro():
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/not_in_loop.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/not_in_loop.py", line 7
    continue # [not-in-loop]
SyntaxError: 'continue' not properly in loop

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/raising_non_exception_py3.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/raising_non_exception_py3.py", line 13
    raise Exc from missing # [raising-non-exception]
                 ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/return_outside_function.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/return_outside_function.py", line 2
    return # [return-outside-function]
SyntaxError: 'return' outside function

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/star_needs_assignment_target.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/star_needs_assignment_target.py", line 3
    FIRST = *[1, 2]  # [star-needs-assignment-target]
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/star_needs_assignment_target_py35.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/star_needs_assignment_target_py35.py", line 8
    UNPACK_TUPLE = (*range(4), 4)
                    ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/syntax_error.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/syntax_error.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/syntax_error_jython.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/syntax_error_jython.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/too_many_star_expressions.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/too_many_star_expressions.py", line 3
    *FIRST, *SECOND = [1, 2, 3] # [too-many-star-expressions]
    ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/unbalanced_tuple_unpacking_py30.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/unbalanced_tuple_unpacking_py30.py", line 9
    first, second, *last = (1, 2, 3, 4)
                   ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/undefined_variable_py30.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/undefined_variable_py30.py", line 8
    def test(self)->Undefined: # [undefined-variable]
                  ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/unpacking_generalizations.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/unpacking_generalizations.py", line 16
    func_variadic_args(*(2, 3), *(3, 4), *(4, 5))
                                ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/used_before_assignment_nonlocal.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/used_before_assignment_nonlocal.py", line 10
    nonlocal cnt
               ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_from_iterable_py33.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_from_iterable_py33.py", line 7
    yield from 10  # [not-an-iterable]
             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_from_outside_func.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_from_outside_func.py", line 2
    yield from [1, 2]  # [yield-outside-function]
             ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_inside_async_function.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_inside_async_function.py", line 4
    async def good_coro():
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_outside_func.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/functional/yield_outside_func.py", line 2
    yield 1  # [yield-outside-function]
SyntaxError: 'yield' outside function

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_kwoa_py30.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_kwoa_py30.py", line 3
    def function(*, foo):
                  ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_return_yield_mix_py_33.py ...
SyntaxError: 'return' with argument inside generator (func_return_yield_mix_py_33.py, line 8)

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_unused_import_py30.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_unused_import_py30.py", line 10
    class Meta(metaclass=abc.ABCMeta):
                        ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_w0705.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/input/func_w0705.py", line 28
    __revision__ += 1
SyntaxError: default 'except:' must be last

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/input/syntax_error.py ...
Sorry: IndentationError: expected an indented block (syntax_error.py, line 2)
Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/regrtest_data/bad_package/__init__.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/regrtest_data/bad_package/__init__.py", line 2
    raise missing.Missing..
                          ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-wMSfMK/pylint/pylint/test/regrtest_data/syntax_error.py ...
  File "/tmp/pip-build-wMSfMK/pylint/pylint/test/regrtest_data/syntax_error.py", line 1
    class A extends B {}
                  ^
SyntaxError: invalid syntax

  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for simplegeneric
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/replicated/www/default/admindir/edpcmentoring/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/replicated/www/default/admindir/edpcmentoring/env/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/replicated/www/default/admindir/edpcmentoring/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named packaging.version
    Complete output from command /replicated/www/default/admindir/edpcmentoring/env/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-wMSfMK/simplegeneric/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Dn8iRb-record/install-record.txt --single-version-externally-managed --compile --install-headers /replicated/www/default/admindir/edpcmentoring/env/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/replicated/www/default/admindir/edpcmentoring/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/replicated/www/default/admindir/edpcmentoring/env/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/replicated/www/default/admindir/edpcmentoring/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command /replicated/www/default/admindir/edpcmentoring/env/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-wMSfMK/simplegeneric/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Dn8iRb-record/install-record.txt --single-version-externally-managed --compile --install-headers /replicated/www/default/admindir/edpcmentoring/env/include/site/python2.7 failed with error code 1 in /tmp/pip-build-wMSfMK/simplegeneric

**Comment by S-Stephen** [comment]
adding:

appdirs
packages

to requirements_mws3.txt helped complete the build (though there were a few errors from a couple of packages)

Thanks Rich
